Add dependencies to Readme and further functions to tcpdump
Signed-off-by: Stefan Venz <stefan.venz@protonmail.com>

diff --git a/con-test/wireless_monitor b/con-test/wireless_monitor
--- a/con-test/wireless_monitor
+++ b/con-test/wireless_monitor
@@ -65,6 +65,7 @@ check_monitor()
 # Arguemnts:
 # interface - use this interface for tcpdump
 # file_name - name for log file
+# time - amount of seconds tcpdump runs
 #
 start_client_tcpdump()
 {
@@ -74,12 +75,37 @@ start_client_tcpdump()
 	if (( $C_AUTH == 1)); then
 		ret=$(nohup sshpass -p "$CLIENT_PASSWORD" \
 			     ssh ${CLIENT_USER}@${CLIENT_IP} \
-			     "tcpdump -w ${LOG_PATH}/$file_name -i $interface")
+			     "timeout $time tcpdump -w ${LOG_PATH}/$file_name -i $interface")
 		check_ret_val $? "something went wrong starting tcpdump on $CLIENT_IP"
 	else
 		ret=$(nohup ssh -i ${CLIENT_CERTIFICATE} \
 		      ${CLIENT_USER}@${CLIENT_IP} \
-		      "tcpdump -w ${LOG_PATH}/${file_name} -i $interface")
+		      "timeout $time tcpdump -w ${LOG_PATH}/${file_name} -i $interface")
+	fi
+}
+
+# start tcp dump on the server side
+#
+# Arguemnts:
+# interface - use this interface for tcpdump
+# file_name - name for log file
+# time - amount of seconds tcpdump runs
+#
+start_server_tcpdump()
+{
+	interface=$1
+	file_name=$2
+	time=$3
+
+	if (( $C_AUTH == 1)); then
+		ret=$(nohup sshpass -p "$SERVER_PASSWORD" \
+			     ssh ${SERVER_USER}@${SERVER_IP} \
+			     "timeout $time tcpdump -w ${LOG_PATH}/$file_name -i $interface")
+		check_ret_val $? "something went wrong starting tcpdump on $CLIENT_IP"
+	else
+		ret=$(nohup ssh -i ${SERVER_CERTIFICATE} \
+		      ${SERVER_USER}@${SERVER_IP} \
+		      "timeout $time tcpdump -w ${LOG_PATH}/${file_name} -i $interface")
 	fi
 }
 
@@ -90,10 +116,13 @@ start_client_tcpdump()
 main()
 {
 	args=$@
+	time=0
+	interface=''
+
 	test_get_opt
 
-	options=c:hmo:t:V
-	loptions=config:,help,monitor,output:,time:,version
+	options=c:f:hmo:t:V
+	loptions=config:,file:,help,monitor,output:,time:,version
 	config_path="con-test.conf"
 
 	! parsed=$(getopt --options=$options --longoptions=$loptions --name "$0" -- $args)
@@ -107,6 +136,10 @@ main()
 		case "$1" in
 			-c | --config)
 				config_path=$2
+				shift 2
+				;;
+			-f | --file)
+				file_name=$2
 				shift 2
 				;;
 			-h | --help)
@@ -143,6 +176,11 @@ main()
 		esac
 	done
 
+	if [ -z $interface ]; then
+		printf "${ERROR} Please provide an interface for monitoring\n"
+		exit $FAILURE
+	fi
+
 	printf "${INFO} Starting wireless monitor\n"
 	printf "\t\tUsing config ${config_path}\n"
 	printf "\t\tUsing logpath ${LOG_PATH}\n"
@@ -164,9 +202,15 @@ main()
 #		check_ret_val $ret "Failed to set $interface to monitor mode"
 #	fi
 
+	check_monitor $interface
+
 	printf "${INFO} starting monitoring $interface on $CLIENT_IP\n"
-	ret=start_tcpdump $interface
-	check_ret_val $ret "Failed to start tcpdump on $interface"
+	ret=start_client_tcpdump $interface $file_name $time
+	check_ret_val $ret "Failed to start tcpdump on $CLIENT_IP $interface"
+
+	printf "${INFO} starting monitoring $interface on $SERVER_IP\n"
+	ret=start_server_tcpdump $interface $file_name $time
+	check_ret_val $ret "Failed to start tcpdump on $SERVER_IP $interafce"
 }
 
 main $@
